vault:
  kv:
    application-names:
      - management

server:
  port: ${vault:V_SERVER_PORT}
  aes-secret-key: ${vault:V_AES_SECRET_KEY}
  auth:
    admin-login: ${vault:V_DEFAULT_ADMIN_LOGIN}
    session:
      ttl-sec: 3600 # 1h
      sid-token-length: 32 # in bytes
      csrf-token-length: 32 # in bytes
ota:
  token:
    length: 10
    ttl-sec: 600 # 10 minutes

cf:
  captcha:
    verify-endpoint: https://challenges.cloudflare.com/turnstile/v0/siteverify
    secret-key: ${vault:V_CF_CAPTCHA_SECRET_KEY}
